name: cifar
channels:
  - defaults
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.7.2
  - anaconda-auth=0.8.6
  - anaconda-cli-base=0.5.2
  - annotated-types=0.6.0
  - aom=3.6.0
  - archspec=0.2.3
  - asttokens=3.0.0
  - blas=1.0
  - bleach=6.2.0
  - boltons=25.0.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.1
  - conda=25.7.0
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - contourpy=1.3.1
  - cpp-expected=1.1.0
  - cryptography=45.0.5
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distro=1.9.0
  - executing=2.2.1
  - expat=2.7.1
  - fmt=9.1.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozendict=2.4.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2025.0.0
  - ipykernel=6.30.1
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jeepney=0.7.1
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_pygments=0.3.0
  - keyring=25.6.0
  - kiwisolver=1.4.8
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libavif=1.1.1
  - libcups=2.4.2
  - libcurl=8.14.1
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - menuinst=2.3.1
  - mesalib=25.1.5
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - more-itertools=10.3.0
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.2
  - numexpr=2.11.0
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.0.17
  - packaging=25.0
  - pandas=2.3.2
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pkce=1.0.3
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydantic-settings=2.6.1
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.13.7
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.20.0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyzmq=27.1.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readchar=4.0.5
  - readline=8.3
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.4
  - rich=13.9.4
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - scikit-learn=1.7.1
  - scipy=1.16.1
  - secretstorage=3.3.1
  - semver=3.0.2
  - setuptools=72.1.0
  - shellingham=1.5.0
  - simdjson=3.10.1
  - sip=6.10.0
  - six=1.17.0
  - spdlog=1.11.0
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.10.1
      - aiofiles==24.1.0
      - annotated-doc==0.0.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - attrs==25.3.0
      - audioop-lts==0.2.2
      - autograd==1.8.0
      - beautifulsoup4==4.14.2
      - brotli==1.1.0
      - diffusers==0.30.1
      - fastapi==0.120.0
      - fastjsonschema==2.21.2
      - ffmpy==0.6.4
      - filelock==3.19.1
      - fsspec==2025.9.0
      - glcontext==3.0.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - ipdb==0.13.13
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kernels==0.11.1
      - lazy-loader==0.4
      - mistune==3.1.4
      - moderngl==5.12.0
      - moge==2.0.0
      - mpmath==1.3.0
      - networkx==3.5
      - nltk==3.9.1
      - notebook-as-pdf==0.5.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - orjson==3.11.4
      - pipeline==1.0.0
      - protobuf==6.32.1
      - pydub==0.25.1
      - pyee==11.1.1
      - pypdf2==3.0.1
      - pyppeteer==2.0.0
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2025.9.18
      - rpds-py==0.27.1
      - ruff==0.14.2
      - safehttpx==0.1.7
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sniffio==1.3.1
      - soupsieve==2.8
      - starlette==0.48.0
      - sympy==1.13.1
      - tifffile==2025.10.4
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchvision==0.21.0+cu126
      - transformers==4.56.2
      - trimesh==4.9.0
      - triton==3.2.0
      - typer==0.20.0
      - urllib3==1.26.20
      - utils3d==1.3
      - uvicorn==0.38.0
      - websockets==15.0.1
      - xgboost==3.0.5
      - zipp==3.23.0
prefix: /home/sunqi/miniconda3
